using System.Text;

//test
namespace Decorator {

	/// <summary>The message class that is used for all serialization/deserialization transfers</summary>
	public class Message {

		/// <summary>Initializes a new instance of the <see cref="Message"/> class.</summary>
		/// <param name="type">The type.</param>
		/// <param name="args">The arguments.</param>
		/// <autogeneratedoc />
		public Message(string type, params object[] args) {
			this.Type = type;
			this.Args = args;
		}

		/// <summary>Gets the type.</summary>
		/// <value>The type.</value>
		/// <autogeneratedoc />
		public string Type { get; }

		/// <summary>Gets the arguments.</summary>
		/// <value>The arguments.</value>
		/// <autogeneratedoc />
		public object[] Args { get; }

		internal int MatchAmount { get; set; }

		/// <summary>Returns a <see cref="System.String" /> that represents this instance.</summary>
		/// <returns>A <see cref="System.String" /> that represents this instance.</returns>
		/// <autogeneratedoc />
		public override string ToString() {
			var strb = new StringBuilder();

			strb.AppendLine($"Type: {this.Type ?? "null"}");

			for (var i = 0; i < this.Args.Length; i++)
				strb.AppendLine($"\t[{i}] {this.Args[i].GetType()}: {this.Args[i]}");

			return strb.ToString();
		}
	}
}