using System;

namespace Decorator.Attributes {

	/// <summary>
	/// Prevents the message from having any more arguments then the amount specified.
	/// </summary>
	[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
	public sealed class ArgumentLimitAttribute : Attribute {

		/// <summary>Initializes a new instance of the <see cref="ArgumentLimitAttribute" /> class.</summary>
		/// <param name="argLimit">The argument limit.</param>
		/// <autogeneratedoc />
		public ArgumentLimitAttribute(int argLimit) => this.ArgLimit = argLimit;

		/// <summary>Gets or sets the argument limit.</summary>
		/// <value>The argument limit.</value>
		/// <autogeneratedoc />
		public int ArgLimit { get; set; }
	}
}