using System;

namespace Decorator.Attributes {

	/// <summary>
	/// Sets where the position of this attribute is in the message
	/// </summary>
	[AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
	public sealed class PositionAttribute : Attribute {

		/// <summary>Initializes a new instance of the <see cref="PositionAttribute" /> class.</summary>
		/// <param name="position">The position.</param>
		/// <autogeneratedoc />
		public PositionAttribute(int position) => this.Position = position;

		public int Position { get; set; }
	}
}